apiVersion: apps/v1
kind: Deployment

metadata:
  name: microservice-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: microservice-app

  template:
    metadata:
      labels:
        app: microservice-app

    spec:
      containers:
        - name: microservice-app
          image: YOUR_DOCKERHUB_USERNAME/eks-microservices-demo:1.0
          ports:
            - containerPort: 3000
